### ISSUE TITLE
Bug 重复多个搜索icon

### ISSUE THREAD

**Issue by whitfield-lyx** [whitfield-lyx/EcnuTimeBank#6]
似乎从我的需求publishfragment切换到需求列表requirefragment 
每次都会新增一个search的icon
![图片](https://user-images.githubusercontent.com/40332644/82735374-ddf6b200-9d53-11ea-8770-70f9fa2c69a8.png)
![图片](https://user-images.githubusercontent.com/40332644/82735378-e353fc80-9d53-11ea-8bd5-ac415b911011.png)

**Comment by HatsuneMK00** [comment]
我这边好像没这个问题诶？
具体怎么做能复现这个bug？

**Comment by whitfield-lyx** [comment]
惊了 我从第三个模块回到第二个模块的时候每次都会多一个
